Fix clock_gettime() support check for Darwin
Darwin doesn't support clock_gettime() but has _POSIX_MONOTONIC_CLOCK defined
so use a more strict check with HAVE_CLOCK_GETTIME.

This fixes the following compilation error:

  java_lang_VMSystem.c: In function ‘Java_java_lang_VMSystem_nanoTime’:
  java_lang_VMSystem.c:148: warning: implicit declaration of function ‘clock_gettime’
  java_lang_VMSystem.c:148: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
  java_lang_VMSystem.c:148: error: (Each undeclared identifier is reported only once
  java_lang_VMSystem.c:148: error: for each function it appears in.)

2011-07-05  Pekka Enberg  <penberg@kernel.org>

       * configure.ac:
       Check for clock_gettime().
       native/jni/java-lang/java_lang_VMSystem.c:
       (Java_java_lang_VMSystem_nanoTime):
       Fix compile error on systems that don't have clock_gettime().